name: WakaTime Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'
jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          API BASE URL: ${{ secrets.WAKAPI BASE URL }}
          WAKATIME_API_KEY: ${{ secrets WAKAPI_API_KEY }}
          COMMIT MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME RANGE: last_30_days
          SHOW TIME: true
